version: 2.1

os_default: &os_default
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *os_default
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    <<: *os_default
    steps:
      - checkout
      - run: npm i
      - restore_cache:
          keys: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm i
      - run: npm run test

  analyze:
    <<: *os_default
    steps:
      - checkout
      - run: npm audit

workflows:
  build-test-analyze:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
